import Layout from "../Layout/Layout";
import "./Subcategories.css";

function Subcategories(props) {
  return (
    <Layout className="subcategories">
      hello...... hello...... hello...... hello...... hello...... hello......
      hello...... hello...... hello...... hello...... hello...... hello......
      hello...... hello...... hello......
      <div className="di">
        <p>
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
        </p>
        <p>
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
        </p>
        <p>
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
        </p>
        <p>
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
        </p>
        <p>
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
        </p>
        <p>
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
        </p>
        <p>
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
        </p>
        <p>
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
        </p>
        <p>
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
        </p>
        <p>
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
        </p>
        <p>
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
        </p>
        <p>
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
        </p>
        <p>
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
        </p>
        <p>
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
        </p>
        <p>
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
        </p>
        <p>
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
        </p>
        <p>
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
        </p>
        <p>
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
          hello...... hello...... hello...... hello...... hello......
        </p>
      </div>
      {props.categories}
    </Layout>
  );
}

export default Subcategories;
